version: '3.8'

services:
  web:
    build: .
    container_name: php-proyecto
    ports:
      - "8081:80"
      - "9003:9003" # Puerto para el depurador
    volumes:
      - imagenes_data:/var/www/html/imagenes
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: proyecto
      MYSQL_USER: gestor
      MYSQL_PASSWORD: secreto
      MAILTRAP_TOKEN: a14911d8d73e6cd65e1701c1ec080756
      MAILTRAP_INBOX_ID: 4686267

  db:
    image: mysql:8.0
    container_name: mysql-proyecto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secreto
      MYSQL_DATABASE: proyecto
      MYSQL_USER: gestor
      MYSQL_PASSWORD: secreto
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "3308:3306"

volumes:
  db_data:
  imagenes_data:
